export const API_ENDPOINT = {
  HOME: "/ui/home",
  NOTIFICATION: "ui/notifications",
  SETTING: "ui/settings/",
  MENU: "/ui/appview",
  LIGHTING: "ui/lighting",
  LIGHTING_SETTING: "ui/lighting/settings",
  REFRIDGERATOR: "ui/refrigerator/",
  REFRIDGERATOR_FULL_HISTORY: "/ui/refrigerator/fullhistory",
  FREEZER_FULL_HISTORY: "/ui/refrigerator/freezer/fullhistory",
  REFRIDGERATOR_SETTING: "ui/refrigerator/settings",
  CLIMATE_CONTROL: "ui/climate/",
  CLIMATE_CONTROL_SETTING: "ui/climate/settings",
  FUNCTIONALTEST: "ui/functionaltests/",
  ENERGY_MANAGEMENT: "ui/ems/",
  WATER_SYSTEM: "ui/watersystems/",
  WATER_SYSTEM_SETTING: "ui/watersystems/settings",
  INVERTER: "ui/inverter/",
  INVERTER_SETTING: "ui/inverter/settings",
  LOCK_SCREEN: "/api/system/passcode",
  NOTIFICATION_CENTER: "/ui/notifications/center",
  VERSION_DATA: "/version",
  SLIDE_OUT_WARNING: "/ui/movable/so/warning",
  SLIDE_OUT_SETTING: "/ui/movable/so/settings",
  SLIDE_OUT_SCREEN: "/ui/movable/so/screen",
  PAIRING_QR_CODE: "/api/settings/qr_code",
  GENERATOR_SCREEN: "/ui/generator/",
  GENERATOR_SETTING: "/ui/generator/settings",
  MANUFACTURING: "/ui/manufacturing",
  MANUFACTURING_SETTINGS: "/ui/manufacturing/settings",
  AWNING_WARNING: "/ui/movable/aw/warning",
  AWNING_SCREEN: "/ui/movable/aw/screen",
  AWNING_SETTTINGS: "/ui/movable/aw/settings",
  DIAGNOSTICS: "ui/diagnostics",
  DIAGNOSTICS_SETTINGS: "ui/diagnostics/settings",
  PET_MONITORING: "/ui/petmonitoring",
};

export const LOCAL_ENDPOINT = {
  HOME: "home-data",
  HOME_SETTINGS: "home-settings",
  NOTIFICATION: "notification-data",
  SETTING: "setting-data",
  MENU: "menu-data",
  LIGHTING: "lighting-data",
  LIGHTING_SETTING: "lighting-settings-data",
  REFRIDGERATOR: "refrigerator-data",
  REFRIDGERATOR_FULL_HISTORY: "refrigerator-history-data",
  REFRIDGERATOR_SETTING: "refrigerator-setting-data",
  CLIMATE_CONTROL: "climate-control-data",
  CLIMATE_CONTROL_SETTING: "climate-control-setting-data",
  FUNCTIONALTEST: "functionaltests-data",
  ENERGY_MANAGEMENT: "ems-data",
  WATER_SYSTEM: "water-system-data",
  WATER_SYSTEM_SETTING: "water-system-setting-data",
  INVERTER: "inverter-data",
  INVERTER_SETTING: "inverter-setting-data",
  NOTIFICATION_CENTER: "notifications-center",
  VERSION_DATA: "version-data",
  SLIDE_OUT_WARNING: "slide-out-warning",
  SLIDE_OUT_SETTING: "/ui/movable/so/settings",
  SLIDE_OUT_SCREEN: "/ui/movable/so/screen",
  GENERATOR_SCREEN: "/ui/generator/",
  GENERATOR_SETTING: "/ui/generator/settings",
  MANUFACTURING: "manufacturing",
  MANUFACTURING_SETTINGS: "manufacturing-settings",
  AWNING_WARNING: "awning-warning-screen",
  AWNING_SCREEN: "awning-screen",
  AWNING_SETTTINGS: "awning-settings",
  DIAGNOSTICS: "diagnostics",
  DIAGNOSTICS_SETTINGS: "diagnostics-settings",
  PET_MONITORING: "ui-petmonitoring",
};

export const DONT_CACHE = [LOCAL_ENDPOINT.HOME];
